name: 'Deploy to Kubernetes'
on:
  workflow_call:
    inputs:
      microservice-name:
        description: 'Microservice Name to build'
        type: string
        required: true
jobs:
  deploy:
    name: Deploy on Kubernetes
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.microservice-name }}    
    permissions:
      id-token: write
      contents: read  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
