name: 'Deploy to Kubernetes'
on:
  workflow_call:
    inputs:
      application-name:
        description: 'Microservice Name to build'
        required: true
        type: string
jobs:
  print-username:
    name: Deploy on Kubernetes
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  
    steps:
     - name: Config url
            id: config-url 
            shell: bash
            env:
              SERVICE_NAME: ${{ inputs.application-name }}
            run: |-
              echo ${SERVICE_NAME}
