on:
  workflow_call:
    inputs:
      application-name:
        description: 'Microservice Name to build'
        required: true
        type: string
    secrets:
      aws-access-key-id:
        description: 'AWS key id'
        required: true
      aws-secret-access-key:
        description: 'AWS key secret'
        required: true

jobs:
  print-service-name:
    name: Deploy on Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Print Service Name
        run: echo service is ${{ inputs.application-name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose -f ${{ inputs.application-name }}_microservice/docker-compose.yml up -d

      - name: Build, tag, and push image to Amazon ECR
        run: docker-compose -f ${{ inputs.application-name }}_microservice/docker-compose.yml push