on:
  workflow_call:
    inputs:
      application-name:
        description: 'Microservice Name to build'
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS key id'
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS key secret'
        required: true
        type: string

jobs:
  print-service-name:
    name: Deploy on Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Print Service Name
        run: echo service is ${{ inputs.application-name }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
