on:
  workflow_call:
    inputs:
      application-name:
        description: 'Microservice Name to build'
        required: true
        type: string
      image-tag:
        description: 'Docker image tag'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy on Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Print Service Name
        run: echo service is ${{ inputs.application-name }}


      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the docker-compose stack
        env:
          NETWORK_NAME: oauth2
        run: |
          if docker network ls | grep oauth2 -q ; then 
                  echo "network oauth2 already exists. skip"
          else
                  docker network create oauth2 ;
          fi
          make update-env
          make build-${{ inputs.application-name }}
          docker-compose -f ${{ inputs.application-name }}_microservice/docker-compose.yml up -d

#       - name: Run python tests
#         run: make test-${{ inputs.application-name }}

      - name: Build and tag
        env:
          IMAGE_TAG: ${{ inputs.image-tag }}
        run: |
          docker network create oauth || true
          docker tag ${{ inputs.application-name }}_microservice_app ${{ inputs.application-name }}_${{ env.IMAGE_TAG }}
